Deployment/learning_templates/basic_app/urls.py
from django.urls import path, re_path
from basic_app import views

# template tagging 

app_name = 'basic_app'

urlpatterns = [
    re_path('relative/',views.relative,name='relative'),
    path('other/',views.other,name='other'),
    path('base/',views.other,name='other'),
]

Deployment/learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('basic_app/',include('basic_app.urls')),
    path("admin/", admin.site.urls),
]

Deployment/learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

Deployment/learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context={'text':"hello world", 'number':100}
    return render(request,'basic_app/index.html', context)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_templates.html')

Deployment/learning_templates/templates/basic_app/base.html
{%load static%}


<html>
    <head>
        <title> </title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/myStyle.css' %}"/>
    </head>
    <body>
        <h1>Base Page</h1>
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <nav id="nav-bar">
                    <a class="nav-link" href="{% url 'index' %}">BRAND</a>
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    <a class="nav-link" href="{% url 'basic_app:relative' %}">Relative</a>
                  </nav>
                </div>
                </nav>
        <div class="container">
            {% block body_block %}
            {% endblock %}
        </div>
    </body>
</html>

Deployment/learning_templates/templates/basic_app/index.html
<!DOCTYPE html>

{% extends "basic_app/base.html" %}

    {% block body_block %}
    <h1>Index Page</h1>
    {{text | upper }}
    {{text|cut:'sabina'}}
    {{number|add:"2"}}
    {% endblock %}

Deployment/learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block %}
    <h1>Other Page</h1>
    <h2>Example of template inheritance</h2>
    {% endblock %}
 

Deployment/learning_templates/templates/basic_app/relative_url_template.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}

    {% block body_block %}
        <h1>Relative URL Page</h1>
        <a href = "{% url 'basic_app:other' %}">THE OTHER PAGE!</a>
        <a href="{% url 'admin:index' %}">Link to Admin</a>
        <a href="{% url 'index' %}">Link to Index</a>
    
    {% endblock %}